version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:{{KC_TAG}}
    environment:
      KC_HOSTNAME: {{KC_HOSTNAME}}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_PROXY: edge
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db/postgres
    depends_on:
      db:
        condition: service_started
      init:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - {{KC_HOST_PORT}}:8080
    command: ["start"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  keycloak-spare:
    image: quay.io/keycloak/keycloak:{{KC_TAG}}
    environment:
      KC_HOSTNAME: {{KC_HOSTNAME}}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_PROXY: edge
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db/postgres
    depends_on:
      db:
        condition: service_started
      init:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - {{KC_SPARE_HOST_PORT}}:8080
    command: ["start"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    profiles:
      - hot-spare
  db:
    image: postgres:{{POSTGRES_TAG}}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
  backup:
    image: {{UTILS_IMAGE_NAME_TAG}}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GC_BACKUP_BUCKET: {{GC_BACKUP_BUCKET}}
      BACKUP_FILE_NAME: {{BACKUP_FILE_NAME}}
    volumes:
      - ./gc-writer-key.json:/etc/service-account.json
    command: ./backup/entrypoint.sh
  init:
    image: {{UTILS_IMAGE_NAME_TAG}}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGPORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /etc/service-account.json
      GC_BACKUP_BUCKET: {{GC_BACKUP_BUCKET}}
      BACKUP_FILE_NAME: {{BACKUP_FILE_NAME}}
    volumes:
      - ./gc-reader-key.json:/etc/service-account.json
    command: ./init/init.sh
volumes:
  db-data:
